version: '3.4'

services:
  app:
    image: inventdotnetapp:latest
    build:
      context: .
      dockerfile: InventDotnetApp/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=mydb;Username=myuser;Password=mypassword
    depends_on:
      - db
    ports:
      - "5000:80"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
